### PR TITLE
latest kubevirt with volumeName change

### PR DESCRIPTION
**Pull request by karmab**
this needs to be merged only when kubevirt web ui incorporates the corresponding volName attribute removal introduced in 0.13.0

### CODE REVIEW

**Comment by karmab** [comment]
needs https://github.com/kubevirt/web-ui/pull/172 to be merged and latest web ui container to be available

**Comment by jcpowermac** [comment]
@karmab is this for after devconf?

**Comment by karmab** [comment]
> @karmab is this for after devconf?

up to us to decide :)

**Comment by karmab** [comment]
we should merge this @jcpowermac  i believe

**Comment by jcpowermac** [comment]
@karmab sure. That will give me time and others to test to make sure the lab is still good.  I assuming that the image is now available?

**Comment by karmab** [comment]
> @karmab sure. That will give me time and others to test to make sure the lab is still good. I assuming that the image is now available?

yes, latest published today has the proper changes. tested them this morning and everything works fine

**Comment by jcpowermac** [comment]
LGTM

**Pull request merged**
